# Generated by Django 3.0 on 2022-06-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='profit',
        ),
    ]
