# Generated by Django 3.0 on 2022-06-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Transport', 'Transport'), ('Farming', 'Farming'), ('Storage', 'Storage')], max_length=200, null=True)),
                ('predicted_harvest_quantity_in_tonnes', models.FloatField()),
                ('coverage_period_from', models.DateField()),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Insured', 'Insured')], max_length=200, null=True)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Granted', 'Granted')], max_length=200, null=True)),
                ('claim_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Insurance')),
            ],
        ),
    ]
