# Generated by Django 3.0 on 2022-06-11 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_claim_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='coverage_period_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Granted', 'Granted')], default='Submitted', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Insured', 'Insured')], default='Submitted', max_length=200, null=True),
        ),
    ]
